### ISSUE TITLE
Set shippingConfirmation email fails

### ISSUE THREAD

**Issue by calcosta** [kruegge82/dhl-php-sdk#1]
I try to set a confirmation email address for the recipient using the Service Class:

```
$service = new Services();
$service->setShippingConfirmation('test@test.com');
```
That call throws the error `Attempt to assign property "email" on null`.

The problem lies in html `/includes/Services.php` line 621 
`$class->shippingConfirmation->email = $this->getShippingConfirmation();`
where $class->shippingConfirmation is undefined at this moment.

Adding `$class->shippingConfirmation = new StdClass;` before should solve the problem.

**Comment by kruegge82** [comment]
is fixed now in the new version
