### ISSUE TITLE
A json property was not parsable, reason: Invalid format of property value

### ISSUE THREAD

**Issue by jav666** [kruegge82/dhl-php-sdk#3]
The error occurs with international shipments with Customs, as the former ExportDocument. An example of how Customs works with setItems, addItem, setExportDocPosition would be amazing, otherwise it would be almost impossible to solve. Many Tanks and big up for your good Work!

I get this error: How should I start to find the error here? 

`Jahn\DHL\Response Object
(
    [manifestData:Jahn\DHL\Response:private] => 
    [statusCode:Jahn\DHL\Response:private] => 400
    [statusText:Jahn\DHL\Response:private] => Bad Request
    [statusMessage:Jahn\DHL\Response:private] => A json property was not parsable, reason: Invalid format of property value
    [blockType:Jahn\DHL\Response:private] => Blocking Error
    [labelData:Jahn\DHL\Response:private] => Array
        (
        )

    [version:Jahn\DHL\Version:private] => 2.2.1
    [mayor:Jahn\DHL\Version:private] => 2
    [minor:Jahn\DHL\Version:private] => 2
)`

**Comment by kruegge82** [comment]
please try the new version or show us your request.

**Comment by kruegge82** [comment]
Export Example. please look at the updated test.php

**Comment by jav666** [comment]
hello, thank you for the example:. but in my customised test.php with real API access data, as well as your test.php only comes:

_Fatal error: Uncaught Error: Class 'ExportDocPosition' not found in /home/xxxxxxxxxx/public_html/cmssystem/test.php:142 Stack trace: #0 {main} thrown in /home/euwollstud/public_html/cmssystem/test.php on line 142_

edit: please put the line

use Jahn\DHL\ExportDocPosition;

in your test.php

then it works well!

thank you
